# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marc/workspace/synthetic_balls

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marc/workspace/synthetic_balls-build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marc/workspace/synthetic_balls-build/CMakeFiles /home/marc/workspace/synthetic_balls-build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marc/workspace/synthetic_balls-build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named synthetic_balls

# Build rule for target.
synthetic_balls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synthetic_balls
.PHONY : synthetic_balls

# fast build rule for target.
synthetic_balls/fast:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/build
.PHONY : synthetic_balls/fast

ball.o: ball.cpp.o
.PHONY : ball.o

# target to build an object file
ball.cpp.o:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/ball.cpp.o
.PHONY : ball.cpp.o

ball.i: ball.cpp.i
.PHONY : ball.i

# target to preprocess a source file
ball.cpp.i:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/ball.cpp.i
.PHONY : ball.cpp.i

ball.s: ball.cpp.s
.PHONY : ball.s

# target to generate assembly for a file
ball.cpp.s:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/ball.cpp.s
.PHONY : ball.cpp.s

configuration.o: configuration.cpp.o
.PHONY : configuration.o

# target to build an object file
configuration.cpp.o:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/configuration.cpp.o
.PHONY : configuration.cpp.o

configuration.i: configuration.cpp.i
.PHONY : configuration.i

# target to preprocess a source file
configuration.cpp.i:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/configuration.cpp.i
.PHONY : configuration.cpp.i

configuration.s: configuration.cpp.s
.PHONY : configuration.s

# target to generate assembly for a file
configuration.cpp.s:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/configuration.cpp.s
.PHONY : configuration.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/main.cpp.s
.PHONY : main.cpp.s

odes.o: odes.cpp.o
.PHONY : odes.o

# target to build an object file
odes.cpp.o:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/odes.cpp.o
.PHONY : odes.cpp.o

odes.i: odes.cpp.i
.PHONY : odes.i

# target to preprocess a source file
odes.cpp.i:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/odes.cpp.i
.PHONY : odes.cpp.i

odes.s: odes.cpp.s
.PHONY : odes.s

# target to generate assembly for a file
odes.cpp.s:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/odes.cpp.s
.PHONY : odes.cpp.s

plateau.o: plateau.cpp.o
.PHONY : plateau.o

# target to build an object file
plateau.cpp.o:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/plateau.cpp.o
.PHONY : plateau.cpp.o

plateau.i: plateau.cpp.i
.PHONY : plateau.i

# target to preprocess a source file
plateau.cpp.i:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/plateau.cpp.i
.PHONY : plateau.cpp.i

plateau.s: plateau.cpp.s
.PHONY : plateau.s

# target to generate assembly for a file
plateau.cpp.s:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/plateau.cpp.s
.PHONY : plateau.cpp.s

reaction.o: reaction.cpp.o
.PHONY : reaction.o

# target to build an object file
reaction.cpp.o:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/reaction.cpp.o
.PHONY : reaction.cpp.o

reaction.i: reaction.cpp.i
.PHONY : reaction.i

# target to preprocess a source file
reaction.cpp.i:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/reaction.cpp.i
.PHONY : reaction.cpp.i

reaction.s: reaction.cpp.s
.PHONY : reaction.s

# target to generate assembly for a file
reaction.cpp.s:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/reaction.cpp.s
.PHONY : reaction.cpp.s

species.o: species.cpp.o
.PHONY : species.o

# target to build an object file
species.cpp.o:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/species.cpp.o
.PHONY : species.cpp.o

species.i: species.cpp.i
.PHONY : species.i

# target to preprocess a source file
species.cpp.i:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/species.cpp.i
.PHONY : species.cpp.i

species.s: species.cpp.s
.PHONY : species.s

# target to generate assembly for a file
species.cpp.s:
	$(MAKE) -f CMakeFiles/synthetic_balls.dir/build.make CMakeFiles/synthetic_balls.dir/species.cpp.s
.PHONY : species.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... synthetic_balls"
	@echo "... ball.o"
	@echo "... ball.i"
	@echo "... ball.s"
	@echo "... configuration.o"
	@echo "... configuration.i"
	@echo "... configuration.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... odes.o"
	@echo "... odes.i"
	@echo "... odes.s"
	@echo "... plateau.o"
	@echo "... plateau.i"
	@echo "... plateau.s"
	@echo "... reaction.o"
	@echo "... reaction.i"
	@echo "... reaction.s"
	@echo "... species.o"
	@echo "... species.i"
	@echo "... species.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

